language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost/waiter_database

node_js:
        - "v8.10.0"

before_script:

  - psql -c 'create database waiter_database;' -U postgres
  - psql -U postgres -d waiter_database -a -f tables_waiter.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2      